[package]
name = "cool-rs"
version = "0.1.0"
authors = ["Eduardo Lemos Paschoalini"]
edition = "2021"

[build-dependencies]
lalrpop = "0.20.2"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
eyre = "0.6"
lalrpop-util = { version = "0.20.2", features = ["lexer"] }
regex = "1.10"